sudo: false

language: python

dist: xenial

addons:
  apt:
    packages:
      - expect-dev

python:
  - "2.7"
  - "3.5"
  - "3.6"

cache: pip

install: # Only 1 dependency for text_type()
  - pip install six

script:
  - unbuffer python -m unittest discover sacremoses/test/ -v
